admissionController:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
  certManager:
    enabled: true

recommender:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical

updater:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: node-role.kubernetes.io/system
      operator: Exists
      effect: NoSchedule
  priorityClassName: platform-critical
  extraArgs:
    - --min-replicas=1